export const Trigger = [
  'spotify',
  'spotify app',
  'spotify music',
  'spotify song',
  'spotify songs',
  'spotify track',
  'spotify tracks',
  'spotify artist',
  'spotify artists',
  'spotify album',
  'spotify albums',
  'spotify playlist',
  'spotify playlists',
  'my playlists',
  'spotify library',
  'spotify liked songs',
  'spotify saved tracks',
  'spotify queue',
  'spotify player',
  'spotify playback',
  'spotify device',
  'spotify connect',
  'now playing',
  'currently playing',
  'current track',
  'current song',
  'what is playing',
  'play music',
  'pause music',
  'resume music',
  'skip track',
  'next song',
  'previous song',
  'repeat song',
  'shuffle music',
  'volume up',
  'volume down',
  'mute music',
  'unmute music',
  'add to queue',
  'remove from queue',
  'clear queue',
  'create playlist',
  'update playlist',
  'delete playlist',
  'add to playlist',
  'remove from playlist',
  'follow playlist',
  'unfollow playlist',
  'follow artist',
  'unfollow artist',
  'like song',
  'unlike song',
  'save track',
  'remove saved track',
  'search spotify',
  'search song',
  'search artist',
  'search album',
  'search playlist',
  'browse music',
  'discover music',
  'music recommendations',
  'recommended songs',
  'recommended artists',
  'top tracks',
  'top artists',
  'recently played',
  'recent tracks',
  'listening history',
  'spotify radio',
  'start radio',
  'artist radio',
  'song radio',
  'genre radio',
  'spotify charts',
  'trending songs',
  'viral songs',
  'spotify new releases',
  'new music',
  'latest songs',
  'spotify genres',
  'spotify category',
  'spotify moods',
  'workout music',
  'chill music',
  'focus music',
  'party music',
  'sleep music',
  'spotify podcasts',
  'spotify podcast',
  'play podcast',
  'pause podcast',
  'resume podcast',
  'spotify episode',
  'spotify episodes',
  'spotify show',
  'spotify shows',
  'spotify api',
  'spotify sdk',
  'spotify token',
  'spotify auth',
  'spotify login',
  'spotify logout',
  'spotify settings',
  'spotify preferences',
  'spotify help',
  'spotify support',
];
