export const Trigger = [
  'notion',
  'app',
  'workspace',
  'workspaces',
  'page',
  'pages',
  'create page',
  'update page',
  'delete page',
  'duplicate page',
  'move page',
  'share page',
  'public page',
  'private page',
  'database',
  'databases',
  'create database',
  'update database',
  'delete database',
  'query database',
  'filter database',
  'sort database',
  'database schema',
  'properties',
  'property',
  'relation',
  'rollup',
  'select',
  'multi select',
  'checkbox',
  'date',
  'text',
  'number',
  'formula',
  'block',
  'blocks',
  'paragraph block',
  'heading block',
  'list block',
  'todo block',
  'toggle block',
  'code block',
  'embed block',
  'image block',
  'video block',
  'file block',
  'table block',
  'divider block',
  'callout block',
  'quote block',
  'breadcrumb',
  'navigation',
  'search',
  'find',
  'quick find',
  'recent',
  'favorites',
  'sidebar',
  'templates',
  'template',
  'duplicate template',
  'comments',
  'comment',
  'mention',
  'mentions',
  'collaboration',
  'activity',
  'history',
  'version',
  'restore',
  'permissions',
  'roles',
  'access',
  'invite',
  'members',
  'team',
  'teams',
  'guest',
  'guests',
  'integration',
  'integrations',
  'api',
  'sdk',
  'token',
  'auth',
  'webhook',
  'sync',
  'import',
  'export',
  'markdown export',
  'csv export',
  'settings',
  'preferences',
  'dark mode',
  'notifications',
  'help',
  'support',
];
